# PyTorch Basics

Pytorch is a library for creating neural networks in Python. 

This notebook draws heavily from the following sources: 
* Pytorch's official [Tensors notebook](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)
* Phillip Lippe's [Intro to Pytorch notebook](https://github.com/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/tutorial2/Introduction_to_PyTorch.ipynb)

## Overview of the library
* [`torch`](https://pytorch.org/docs/stable/torch.html) The top-level PyTorch package that provides an entry point to all PyTorch modules including the Tensor object.  
* [`torch.nn`](https://pytorch.org/docs/stable/nn.html)  A subpackage that contains modules and classes for building neural networks.
* [`torch.utils.data`](https://pytorch.org/docs/stable/data.html) A subpackage that provides tools for working with data. 
* [`torch.distributed`](https://pytorch.org/docs/stable/distributed.html) A subpackage that provides support for training on multiple gpus and multiple nodes.
* [`torch.autograd`](https://pytorch.org/docs/stable/autograd.html) A package that provides automatic differentiation for all operations on Tensors.
* [`torchvision`](https://pytorch.org/vision/stable/index.html) A package that provides access to popular datasets, model architectures, and image transformations for computer vision.

## Tensors
Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to store:
1. model inputs
2. model outputs
3. model parameters.

Tensors can have _many_ dimensions (at least 10,000 in version 2.0 -- I checked).

Tensors are similar to [NumPy’s](https://numpy.org/) ndarrays, except that tensors can run on GPUs or other hardware accelerators. Tensors are also optimized for automatic differentiation. If you’re familiar with numpy arrays, you’ll be right at home with the Tensor API.

To start working with tensors, we import the top-level Pytorch package:

In [1]:
import torch

# Also our input function
from utils import create_answer_box

### Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**A range of values**

In [2]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# What do you think this will do? Try to predict before running it.
torch.arange(5,15,2)

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From/To a NumPy array**

Tensors can be created from NumPy arrays.



In [5]:
import numpy as np
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)
np_arr_2 = tensor.numpy()

print("Numpy array:\n", np_arr)
print("PyTorch tensor:\n", tensor)
print("Numpy array 2:\n", np_arr_2)

Numpy array:
 [[1 2]
 [3 4]]
PyTorch tensor:
 tensor([[1, 2],
        [3, 4]])
Numpy array 2:
 [[1 2]
 [3 4]]


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5758, 0.0781],
        [0.0811, 0.3958]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0939, 0.4089, 0.3241],
        [0.1277, 0.1425, 0.6626]]) 

Ones Tensor: 
 tensor([[3., 3., 3.],
        [3., 3., 3.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

**Indexing**

We often have the situation where we need to select a part of a tensor. Indexing works just like in numpy, so let's try it:

In [10]:
x = torch.arange(12).view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
x[:, 1]   # Second column

tensor([1, 5, 9])

In [12]:
x[0]      # First row

tensor([0, 1, 2, 3])

In [13]:
x[1:3] # Middle two rows

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# MINI-CHALLENGE: Write a line that gives us the first two rows and last column of x


In [ ]:
create_answer_box("What code gives us the first two rows and last column of x?", "01-01")

**adding/removing indices**

We often need to add empty indices.

In [14]:
print(x.shape)
print(x[None].shape) # add new index at front

torch.Size([3, 4])
torch.Size([1, 3, 4])


In [15]:
x[:, None].shape # in the 2nd position

torch.Size([3, 1, 4])

In [16]:
x[..., None].shape # in the last position

torch.Size([3, 4, 1])

`unsqueeze` accomplishes the same thing

In [17]:
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(-1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


We can remove empty indices as well.

In [18]:
x = torch.randn(1,3,1,1,4)
x.shape

torch.Size([1, 3, 1, 1, 4])

In [19]:
x[0].shape

torch.Size([3, 1, 1, 4])

In [20]:
x.squeeze().shape

torch.Size([3, 4])

**Changing the shape**
There are many ways

In [21]:
x = torch.randn(2,3)
x, x.shape

(tensor([[-1.2082,  0.5976,  0.4627],
         [ 0.5930, -1.5669, -0.5785]]),
 torch.Size([2, 3]))

In [22]:
x.T, x.T.shape  # transpose

(tensor([[-1.2082,  0.5930],
         [ 0.5976, -1.5669],
         [ 0.4627, -0.5785]]),
 torch.Size([3, 2]))

In [23]:
x.reshape(3,2)

tensor([[-1.2082,  0.5976],
        [ 0.4627,  0.5930],
        [-1.5669, -0.5785]])

In [ ]:
# MINI-CHALLENGE: Reshape x to a 1D tensor. There are at least 5 ways to do this -- can you find two?


In [ ]:
create_answer_box("Paste in your method(s) for reshaping x to a 1D tensor", "01-02")

Shapes must be compatible

In [26]:
try:
    print(x.reshape(1,6))
except RuntimeError as e:
    print(e)

tensor([[-1.2082,  0.5976,  0.4627,  0.5930, -1.5669, -0.5785]])


`permute` allows us to rearrange indices more flexibly

In [27]:
# create a tensor to play with
y = torch.arange(24).reshape(2,3,4)
y, y.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [28]:
y.permute(1, 0, 2).shape

torch.Size([3, 2, 4])

In [ ]:
y.permute(0,2,1).shape

In [ ]:
create_answer_box(
    "SCENARIO: You have image data (called `data`) shaped (batch_size, height, width, channels) but your model expects (batch_size, channels, height, width). How would you fix this with permute?", 
    "01-03"
)

**Joining tensors** 

You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)_,
another tensor joining option that is subtly different from ``torch.cat``.

In [29]:
tensor = torch.arange(12).reshape(3,4)
tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [30]:
torch.cat([tensor, tensor, tensor], dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])

Sometimes, you want to create a new dimension when combining:

In [32]:
stacked_tensor = torch.stack([tensor, tensor])
print(stacked_tensor)
print(stacked_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
torch.Size([2, 3, 4])


**Arithmetic operations**



In [33]:
# This computes the matrix multiplication between two tensors. y1, y2 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y1, y2, y1-y2

(tensor([[ 14,  38,  62],
         [ 38, 126, 214],
         [ 62, 214, 366]]),
 tensor([[ 14,  38,  62],
         [ 38, 126, 214],
         [ 62, 214, 366]]),
 tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]))

In [34]:
# This computes the element-wise product. z1, z2 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z1, z2, z1-z2

(tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]]),
 tensor([[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]]),
 tensor([[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]))

**aggregations**

In [35]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
# sum, mean, std, etc.
x.sum(), x.mean(), x.std()

(tensor(66.), tensor(5.5000), tensor(3.6056))

In [38]:
# sum along first axis
print(x.sum(axis=0))

# or second
x.sum(axis=1)

tensor([12., 15., 18., 21.])


tensor([ 6., 22., 38.])